- name: install git
  apt:
    name: git
    state: present
    force: yes
  become: true

- name: check if corr is present
  stat: path="{{ corr_path }}/.git"
  register: corr_cloned

- name: clone corr repository
  git:
    repo: https://github.com/{{ corr_repo }}.git
    dest: "{{ corr_path }}"
    version: "{{ corr_version }}"
  when: corr_cloned.stat.exists == False

- name: check if anaconda is installed
  stat: path={{ anaconda_path }}
  register: anaconda_dir

- name: download miniconda
  get_url:
    url: https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
    dest: /tmp
    force: no
  when: anaconda_dir.stat.exists == False

- name: install miniconda
  shell: bash /tmp/Miniconda-latest-Linux-x86_64.sh -b -p {{ anaconda_path }}
  args:
    creates: "{{ anaconda_path }}"
  when: anaconda_dir.stat.exists == False

- name: update conda
  shell: "{{ conda }} update conda"
  when: anaconda_dir.stat.exists == False

- name: check if conda environment exists
  stat: path="{{ anaconda_path }}/envs/{{ corr_env }}"
  register: corr_env_dir

- name: create corr conda env
  shell: "{{ conda }} create -n {{ corr_env }} python"
  when: corr_env_dir.stat.exists == False

- name: install required corrdb packages
  shell: "{{ conda }} env update -n {{ corr_env }} --file {{ corr_path }}/builds/requirements.yaml"
