## Dockerfile to create devel version of CoRR

FROM ubuntu:15.10
MAINTAINER wd15 "https://github.com/wd15"
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -y update
RUN apt-get install -y sudo
RUN apt-get install -y apt-utils
RUN apt-get install -y ansible
VOLUME ["/data/db"]
## Create a user with no sudo password.

RUN useradd -m testuser
RUN passwd -d testuser
RUN adduser testuser sudo
RUN echo 'testuser ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER testuser
WORKDIR /home/testuser
COPY config.bash docker/
COPY builds docker/builds
RUN sudo chown testuser:testuser docker -R

WORKDIR /home/testuser/docker

## Install everything using the Ansible playbook

RUN ./config.bash --tags "install_develop" -vvvv

#CMD ./install.bash --tags "serve_develop"
EXPOSE 4000
