- name: playbook to install CoRR
  hosts: all
  serial: 1
  vars:
    local_path: "{{ lookup('env', 'HOME') }}"
    anaconda_path: "{{ local_path }}/{{ anacondadir }}"
    default_corr_path: "{{ local_path }}/corr"
    remote_user: "{{ lookup('env', 'USER') }}"
    conda: "{{ anaconda_path }}/bin/conda"
    env_path: "{{ anaconda_path }}/envs/{{ corr_env }}/bin"
    python: "{{ anaconda_path }}/envs/{{ corr_env }}/bin/python"
    gunicorn_config: "{{ local_path }}/{{ gunicorn_config_rel }}"
  tasks:

    - include: clone.yaml
      tags: [always]

    - include: mongo.yaml
      when: inventory_hostname in groups['db']
      tags: [install]

    - include: conda.yaml
      when: >
        inventory_hostname in groups['db'] or
        inventory_hostname in groups['api'] or
        inventory_hostname in groups['cloud']
      tags: [install]

    - include: corrdb.yaml
      when: >
        inventory_hostname in groups['db'] or
        inventory_hostname in groups['api'] or
        inventory_hostname in groups['cloud']
      tags: [install]

    - include: view.yaml
      when: >
        ansible_ssh_host == 'localhost' and
        inventory_hostname in groups['frontend']
      tags: [install]

    - name: copy api config file
      when: inventory_hostname in groups['api']
      template: src={{ corr_path }}/builds/config-api.py.j2 dest={{ corr_path }}/corr-api/config.py
      tags: [install]

    - name: copy cloud config file
      when: inventory_hostname in groups['cloud']
      template: src={{ corr_path }}/builds/config-cloud.py.j2 dest={{ corr_path }}/corr-cloud/config.py
      tags: [install]

    - name: copy stormpath config file
      when: inventory_hostname in groups['cloud']
      template: src={{ corr_path }}/builds/apiKey.properties.j2 dest={{ corr_path }}/corr-cloud/apiKey.properties
      tags: [install]

    - include: serve_db.yaml
      when: inventory_hostname in groups['db']
      tags: [serve]

    - include: serve_app.yaml
      when: inventory_hostname in groups['api']
      tags: [serve]
      vars:
        app_path: "{{ corr_path }}/corr-api"

    - include: serve_app.yaml
      when: inventory_hostname in groups['cloud']
      tags: [serve]
      vars:
        app_path: "{{ corr_path }}/corr-cloud"

    - include: serve_frontend.yaml
      when: inventory_hostname in groups['frontend']
      tags: [serve]
