- name: playbook to install CoRR
  hosts: localhost
  connection: local
  vars:
    local_path: "{{ lookup('env', 'HOME') }}"
    anaconda_path: "{{ local_path }}/anaconda"
    default_corr_path: "{{ local_path }}/corr"
    corr_env: corr
    corr_version: master
    corr_repo: usnistgov/corr
    conda: "{{ anaconda_path }}/bin/conda"
    env_path: "{{ anaconda_path }}/envs/{{ corr_env }}/bin"
    python: "{{ anaconda_path }}/envs/{{ corr_env }}/bin/python"
  tasks:
    - include: clone.yaml
      tags:
        - always

    - name: define variable so tasks only run when tags specified
      shell: /bin/true
      register: normal_task_list

    - include: mongo.yaml
      when: normal_task_list is not defined
      tags: [install_db, install_develop]

    - include: conda.yaml
      when: normal_task_list is not defined
      tags: [install_api, install_cloud, install_db, install_develop]

    - include: corrdb.yaml
      when: normal_task_list is not defined
      tags: [install_api, install_cloud, install_db, install_develop]

    - include: view.yaml
      when: normal_task_list is not defined
      tags: [install_develop]

    - include: develop.yaml
      when: normal_task_list is not defined
      tags: [serve_develop]
